cShareSystems.load_pas("Team Burning Systems", [
	"coui://ui/mods/Team_Burning_Systems/systems/[tbs]caladan.pas",
	"coui://ui/mods/Team_Burning_Systems/systems/[tbs]canopus_system.pas",
	"coui://ui/mods/Team_Burning_Systems/systems/[tbs]gemini_belt.pas",
	"coui://ui/mods/Team_Burning_Systems/systems/[tbs]grumman.pas",
	"coui://ui/mods/Team_Burning_Systems/systems/[tbs]halo.pas",
	"coui://ui/mods/Team_Burning_Systems/systems/[tbs]l@v@_c@rn@ge.pas",
	"coui://ui/mods/Team_Burning_Systems/systems/[tbs]lavanos.pas",
	"coui://ui/mods/Team_Burning_Systems/systems/[tbs]lunimos.pas",
	"coui://ui/mods/Team_Burning_Systems/systems/[tbs]metageddon.pas",
	"coui://ui/mods/Team_Burning_Systems/systems/[tbs]pazokia.pas",
	"coui://ui/mods/Team_Burning_Systems/systems/[tbs]pwnageddon.pas",
	"coui://ui/mods/Team_Burning_Systems/systems/[tbs]the_t3mple 2v2.pas",
	"coui://ui/mods/Team_Burning_Systems/systems/[tbs]the_t3mple 3v3.pas",
]);